=== Lucho00Cuba/ASYR-Marcas/UF1/Actividad/eeuu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- ALL -->
<xs:element name="nombre" type="xs:string"/>
<xs:element name="poblacion" type="xs:string"/>
<xs:element name="continente" type="xs:string"/>
<xs:element name="capital" type="xs:string"/>
<xs:element name="latitud" type="xs:decimal"/>
<xs:element name="longitud" type="xs:decimal"/>
<xs:element name="descripcion" type="xs:string"/>
<xs:element name="url" type="xs:string"/>
<xs:element name="costa" type="xs:boolean"/>

<!-- Complex -->
<xs:element name="coordenadas">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="latitud"/>
            <xs:element ref="longitud"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="imagenes">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="descripcion"/>
            <xs:element ref="url"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- MAIN -->
<xs:element name="pais">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="poblacion"/>
            <xs:element ref="continente"/>
            <xs:element ref="capital"/>
            <xs:element ref="coordenadas"/>
            <xs:element ref="imagenes"/>
            <xs:element ref="costa"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Lucho00Cuba/ASYR-Marcas/UF1/Actividad/eeuu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pais [
    <!ELEMENT pais (nombre, poblacion, continente, capital, coordenadas+, imagenes+, costa)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
    <!ELEMENT coordenadas (latitud, longitud)>
    <!ELEMENT latitud (#PCDATA)>
    <!ELEMENT longitud (#PCDATA)>
    <!ELEMENT imagenes (nombre, descripcion, url)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT url (#PCDATA)>
    <!ELEMENT costa (#PCDATA)>
]>
<pais xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./eeuu.xsd">
    <nombre>EEUU</nombre>
    <poblacion>10</poblacion>
    <continente>America</continente>
    <capital>Washington</capital>
    <coordenadas>
        <latitud>37.09024</latitud>
        <longitud>-95.712891</longitud>
    </coordenadas>
    <imagenes>
        <nombre>Hell's Kitchen</nombre>
        <descripcion>Barrio de los teatros y es hogar de actores</descripcion>
        <url>https://es.wikipedia.org/wiki/Hell%27s_Kitchen_(Manhattan)</url>
    </imagenes>
    <costa>true</costa>
</pais>
